### ISSUE TITLE
Duke suddenly just does not run anymore.

### ISSUE THREAD

**Issue by ning-sy210** [nus-cs2103-AY1920S1/forum#86]
## Environment

Describe your development environment

- IntelliJ version: IntelliJ IDEA Community Edition 2019.2.2 x64
- Java version: 12.0.2
- Operating system version: Windows 10 1903
- _other packages' versions_

## Issue

Duke was running perfectly fine in Intellij when I input "gradlew run" into the console. So I created the jar file for Duke and tried running it, the Duke program loads when the jar file is run. However, Duke is now completely incapable of reading/writing into a local save file. 

Going back into Intellij, when I input "gradlew run" into the terminal again, I'm being thrown a bunch of error messages which I do not know the cause of. 

The code block below contains the errors that I faced when I input "gradlew run".
```
  > Task :run FAILED
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class duke.Main
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:890)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:802)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: java.time.format.DateTimeParseException: Text '12/12/12 1000-1800' could not be parsed, unparsed text found at index 13
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1951)
        at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:492)
        at misc.Parser.formatDeadline(Parser.java:153)
        at misc.Parser.convertStringToTime(Parser.java:90)
        at task.Deadline.<init>(Deadline.java:32)
        at misc.Parser.readTextAsTask(Parser.java:64)
        at misc.Storage.readTasksIntoTaskList(Storage.java:87)
        at misc.Storage.readSaveFile(Storage.java:77)
        at duke.Duke.<init>(Duke.java:33)
        at duke.Main.<init>(Main.java:16)
        ... 14 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
3 actionable tasks: 1 executed, 2 up-to-date

```

**Comment by geshuming** [comment]
Just look at the exception thrown by your java files: 

```
Caused by: java.time.format.DateTimeParseException: Text '12/12/12 1000-1800' could not be parsed, unparsed text found at index 13
        at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
        at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1951)
        at java.base/java.time.LocalDateTime.parse(LocalDateTime.java:492)
        at misc.Parser.formatDeadline(Parser.java:153)
        at misc.Parser.convertStringToTime(Parser.java:90)
        at task.Deadline.<init>(Deadline.java:32)
        at misc.Parser.readTextAsTask(Parser.java:64)
        at misc.Storage.readTasksIntoTaskList(Storage.java:87)
        at misc.Storage.readSaveFile(Storage.java:77)
        at duke.Duke.<init>(Duke.java:33)
        at duke.Main.<init>(Main.java:16)
        ... 14 more
```

It seems like your deadline object is trying to parse an event datetime string, hence the errors.

**Comment by ning-sy210** [comment]
I wouldn't think it's an error with any of my java files in the project. Like I mentioned, the only thing that I did was creating a JAR file. I did no modifications whatsoever to the java files so I wouldn't think that the error lies there. Plus, when I sent the same JAR file to a friend of mine, he was able to run it without any problems. 

More specifically, I'm particularly concerned about these lines right here:
```
* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1
```

It seems something is wrong with the jdk instead, and I don't know what it is.

**Comment by geshuming** [comment]
Nothing wrong with the above output, but the stack trace shows there might be a problem with your storage parsing. 

I'm just guessing it's untested behavior from saving an event task and loading it (somehow tries to load it as a deadline task). You can try clearing your savefile and see if your jar file opens without issue?

**Comment by ning-sy210** [comment]
Wow thanks, deleting the saved file worked. I figured out that there was an entry in the save file that was written incorrectly, which resulted in the parse error.

**Comment by damithc** [comment]
Thanks for the help @geshuming
