### ISSUE TITLE
Junit Tests not able to run.

### ISSUE THREAD

**Issue by ning-sy210** [nus-cs2103-AY1920S1/forum#90]
## Environment

Describe your development environment

- IntelliJ version: Intellij IDEA Community Edition 2019.2.2 x64
- Java version: 11.0.4
- Operating system version: Windows 10 Home 1903

## Log Trace

```
"C:\Program Files\Java\jdk-11.0.4\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2\lib\idea_rt.jar=58181:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2\plugins\junit\lib\junit5-rt.jar;C:\Users\NINGS\.gradle\caches\modules-2\files-2.1\org.junit.jupiter\junit-jupiter-api\5.4.0\1a09f25a160f71c267f9ebe3b229b17805c683e9\junit-jupiter-api-5.4.0.jar;C:\Users\NINGS\.gradle\caches\modules-2\files-2.1\org.openjfx\javafx-base\11\ad3a4acfaa28b484d30c40c1f009445cc3f6e68b\javafx-base-11-win.jar" com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit5 @w@C:\Users\NINGS\AppData\Local\Temp\idea_working_dirs_junit.tmp @C:\Users\NINGS\AppData\Local\Temp\idea_junit.tmp -socket58180
Exception in thread "main" java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:45)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more
```
The attached are my settings for Gradle in Intellij. The problem here is that I can't run Junit tests by right-clicking but the same operation can be done using gradlew test. I can't seem to find the reason as to why this is happening.

![capture](https://user-images.githubusercontent.com/54129748/65566454-7a7a7180-df85-11e9-8db9-430874de332d.png)

**Comment by j-lum** [comment]
Seems like you're not using Gradle to run your tests from IntelliJ. In that case, make sure that your classpath is set properly.

![image](https://user-images.githubusercontent.com/22460123/65577786-1668a500-dfa7-11e9-9ac9-e4775e506799.png)

This screenshot is from AB3 but you should get the idea.

**Comment by damithc** [comment]
@ning-sy210 resolved?
